// src/features/driver/services/mock.data.ts
// Datos de prueba para el chofer — se usan cuando no hay backend ni caché offline

import type { CachedStop } from './offline.service'

export const MOCK_STOPS: CachedStop[] = [
    {
        id: 'mock-stop-001',
        stopNumber: 1,
        trackingCode: 'TRK-DEMO-20260409-001',
        status: 'EN_RUTA',
        clientName: 'María González',
        clientPhone: '0414-123-4567',
        address: 'Urb. Santa Mónica, Av. Principal, Casa #45, Caracas',
        addressNotes: 'Casa color amarillo con portón negro, tocar timbre dos veces',
        lat: 10.4880,
        lng: -66.8790,
        packageWeight: 2.5,
        packageVolume: '30×20×15 cm',
        packageNotes: 'Frágil — manejar con cuidado',
        estimatedTime: '09:30',
    },
    {
        id: 'mock-stop-002',
        stopNumber: 2,
        trackingCode: 'TRK-DEMO-20260409-002',
        status: 'PENDIENTE',
        clientName: 'Carlos Rodríguez',
        clientPhone: '0424-987-6543',
        address: 'El Paraíso, Calle Los Mangos, Edif. El Jardín, Piso 3, Apto 3B',
        addressNotes: 'Dejar con el conserje si no hay nadie',
        packageWeight: 0.8,
        estimatedTime: '10:15',
    },
    {
        id: 'mock-stop-003',
        stopNumber: 3,
        trackingCode: 'TRK-DEMO-20260409-003',
        status: 'PENDIENTE',
        clientName: 'Luisa Martínez',
        clientPhone: '0412-555-7890',
        address: 'Las Mercedes, C.C. Paseo Las Mercedes, Local 24, Caracas',
        packageWeight: 1.2,
        packageVolume: '25×15×10 cm',
        estimatedTime: '11:00',
    },
    {
        id: 'mock-stop-004',
        stopNumber: 4,
        trackingCode: 'TRK-DEMO-20260409-004',
        status: 'ENTREGADO',
        clientName: 'Andrés Pérez',
        clientPhone: '0416-321-0987',
        address: 'Chacao, Av. Francisco de Miranda, Torre Británica, Piso 8',
        packageWeight: 3.0,
        estimatedTime: '08:00',
        completedAt: new Date(Date.now() - 3600000).toISOString(),
        receiverName: 'Andrés Pérez',
    },
    {
        id: 'mock-stop-005',
        stopNumber: 5,
        trackingCode: 'TRK-DEMO-20260409-005',
        status: 'PENDIENTE',
        clientName: 'Valentina Torres',
        clientPhone: '0426-111-2233',
        address: 'Baruta, Urb. Colinas de Bello Monte, Calle 3, Qta. Las Palmas',
        addressNotes: 'Quinta con jardín al frente, campana en la reja',
        packageWeight: 5.5,
        packageVolume: '50×40×30 cm',
        packageNotes: 'Contiene electrodoméstico — no volcar',
        estimatedTime: '12:30',
    },
]